# Generated by Django 2.1.3 on 2018-11-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_mail_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_auth.EveUser'),
        ),
    ]
