# Generated by Django 2.0.9 on 2018-10-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InvType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eve_sde.Constellation')),
                ('gates', models.ManyToManyField(related_name='_solarsystem_gates_+', to='eve_sde.SolarSystem')),
            ],
        ),
        migrations.AddField(
            model_name='constellation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eve_sde.Region'),
        ),
    ]
