# Generated by Django 4.0.8 on 2023-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarsystem",
            name="gates",
            field=models.ManyToManyField(to="eve_sde.solarsystem"),
        ),
    ]
