name: mutaplasmid-prod

secrets:
  postgres_password:
    file: ./secrets/pg_password.prod.txt
  configuration:
    file: ./secrets/configuration.prod.yaml
  grafana_password:
    file: ./secrets/grafana_password.prod.txt

services:
  server:
    entrypoint: /code/run/server.prod.sh
  frontend:
    entrypoint: /code/run/prod.sh
