# Generated by Django 2.1.3 on 2018-12-01 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eve_auth", "0007_change_character_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="eveuser",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                related_name="characters",
            ),
            preserve_default=False,
        ),
    ]
