# Generated by Django 4.1.13 on 2024-01-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "abyssal_modules",
            "0020_alter_module_attributes_alter_moduletype_attributes_and_more",
        ),
        ("price_predictor", "0002_add_scaler"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricePredictionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=32),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="price_predictor.pricepredictor",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abyssal_modules.module",
                    ),
                ),
            ],
        ),
    ]
