# Generated by Django 2.0.5 on 2018-09-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abyssal_modules', '0004_move_dogma_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRequestAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.ModuleDogmaAttribute')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability_alerts.AlertRequest')),
            ],
        ),
        migrations.AddField(
            model_name='alertrequest',
            name='attributes',
            field=models.ManyToManyField(through='availability_alerts.AlertRequestAttributes', to='abyssal_modules.ModuleDogmaAttribute'),
        ),
        migrations.AddField(
            model_name='alertrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.ModuleType'),
        ),
    ]
