# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PostCharactersCharacterIdFittingsFitting(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'items': 'list[PostCharactersCharacterIdFittingsItem]',
        'name': 'str',
        'ship_type_id': 'int'
    }

    attribute_map = {
        'description': 'description',
        'items': 'items',
        'name': 'name',
        'ship_type_id': 'ship_type_id'
    }

    def __init__(self, description=None, items=None, name=None, ship_type_id=None, _configuration=None):  # noqa: E501
        """PostCharactersCharacterIdFittingsFitting - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._items = None
        self._name = None
        self._ship_type_id = None
        self.discriminator = None

        self.description = description
        self.items = items
        self.name = name
        self.ship_type_id = ship_type_id

    @property
    def description(self):
        """Gets the description of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501

        description string  # noqa: E501

        :return: The description of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PostCharactersCharacterIdFittingsFitting.

        description string  # noqa: E501

        :param description: The description of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                description is not None and len(description) > 500):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `500`")  # noqa: E501
        if (self._configuration.client_side_validation and
                description is not None and len(description) < 0):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def items(self):
        """Gets the items of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501

        items array  # noqa: E501

        :return: The items of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :rtype: list[PostCharactersCharacterIdFittingsItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PostCharactersCharacterIdFittingsFitting.

        items array  # noqa: E501

        :param items: The items of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :type: list[PostCharactersCharacterIdFittingsItem]
        """
        if self._configuration.client_side_validation and items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def name(self):
        """Gets the name of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501

        name string  # noqa: E501

        :return: The name of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PostCharactersCharacterIdFittingsFitting.

        name string  # noqa: E501

        :param name: The name of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 50):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `50`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def ship_type_id(self):
        """Gets the ship_type_id of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501

        ship_type_id integer  # noqa: E501

        :return: The ship_type_id of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :rtype: int
        """
        return self._ship_type_id

    @ship_type_id.setter
    def ship_type_id(self, ship_type_id):
        """Sets the ship_type_id of this PostCharactersCharacterIdFittingsFitting.

        ship_type_id integer  # noqa: E501

        :param ship_type_id: The ship_type_id of this PostCharactersCharacterIdFittingsFitting.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and ship_type_id is None:
            raise ValueError("Invalid value for `ship_type_id`, must not be `None`")  # noqa: E501

        self._ship_type_id = ship_type_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostCharactersCharacterIdFittingsFitting, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostCharactersCharacterIdFittingsFitting):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PostCharactersCharacterIdFittingsFitting):
            return True

        return self.to_dict() != other.to_dict()
