# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PutFleetsFleetIdMembersMemberIdMovement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'str',
        'squad_id': 'int',
        'wing_id': 'int'
    }

    attribute_map = {
        'role': 'role',
        'squad_id': 'squad_id',
        'wing_id': 'wing_id'
    }

    def __init__(self, role=None, squad_id=None, wing_id=None, _configuration=None):  # noqa: E501
        """PutFleetsFleetIdMembersMemberIdMovement - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._role = None
        self._squad_id = None
        self._wing_id = None
        self.discriminator = None

        self.role = role
        if squad_id is not None:
            self.squad_id = squad_id
        if wing_id is not None:
            self.wing_id = wing_id

    @property
    def role(self):
        """Gets the role of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501

        If a character is moved to the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is moved to the `wing_commander` role, only `wing_id` should be specified. If a character is moved to the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is moved to the `squad_member` role, both `wing_id` and `squad_id` should be specified.  # noqa: E501

        :return: The role of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this PutFleetsFleetIdMembersMemberIdMovement.

        If a character is moved to the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is moved to the `wing_commander` role, only `wing_id` should be specified. If a character is moved to the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is moved to the `squad_member` role, both `wing_id` and `squad_id` should be specified.  # noqa: E501

        :param role: The role of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501
        allowed_values = ["fleet_commander", "wing_commander", "squad_commander", "squad_member"]  # noqa: E501
        if (self._configuration.client_side_validation and
                role not in allowed_values):
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"  # noqa: E501
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def squad_id(self):
        """Gets the squad_id of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501

        squad_id integer  # noqa: E501

        :return: The squad_id of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501
        :rtype: int
        """
        return self._squad_id

    @squad_id.setter
    def squad_id(self, squad_id):
        """Sets the squad_id of this PutFleetsFleetIdMembersMemberIdMovement.

        squad_id integer  # noqa: E501

        :param squad_id: The squad_id of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                squad_id is not None and squad_id < 0):  # noqa: E501
            raise ValueError("Invalid value for `squad_id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._squad_id = squad_id

    @property
    def wing_id(self):
        """Gets the wing_id of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501

        wing_id integer  # noqa: E501

        :return: The wing_id of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501
        :rtype: int
        """
        return self._wing_id

    @wing_id.setter
    def wing_id(self, wing_id):
        """Sets the wing_id of this PutFleetsFleetIdMembersMemberIdMovement.

        wing_id integer  # noqa: E501

        :param wing_id: The wing_id of this PutFleetsFleetIdMembersMemberIdMovement.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                wing_id is not None and wing_id < 0):  # noqa: E501
            raise ValueError("Invalid value for `wing_id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._wing_id = wing_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutFleetsFleetIdMembersMemberIdMovement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutFleetsFleetIdMembersMemberIdMovement):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PutFleetsFleetIdMembersMemberIdMovement):
            return True

        return self.to_dict() != other.to_dict()
