# Generated by Django 2.0.5 on 2018-06-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mutator_type_id', models.IntegerField()),
                ('source_type_id', models.IntegerField()),
                ('creator_id', models.BigIntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='abyssal_modules.ModuleType')),
            ],
        ),
    ]
