# Generated by Django 2.0.5 on 2018-08-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershiprecord',
            name='asset_owner',
        ),
        migrations.RemoveField(
            model_name='ownershiprecord',
            name='contract_contract',
        ),
        migrations.RemoveField(
            model_name='ownershiprecord',
            name='module',
        ),
        migrations.DeleteModel(
            name='OwnershipRecord',
        ),
    ]
