# Generated by Django 2.0.5 on 2018-06-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.ModuleDogmaAttribute')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.Module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='attributes',
            field=models.ManyToManyField(related_name='_module_attributes_+', through='abyssal_modules.ModuleAttribute', to='abyssal_modules.ModuleDogmaAttribute'),
        ),
    ]
