# Generated by Django 2.0.5 on 2018-06-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0003_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='module',
            name='creator',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creations', to='abyssal_modules.Creator'),
            preserve_default=False,
        ),
    ]
