# Generated by Django 2.0.5 on 2018-06-11 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0005_rename_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
