# Generated by Django 2.0.5 on 2018-06-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0002_contract_knowledge'),
        ('abyssal_modules', '0006_module_first_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end', models.DateTimeField(db_index=True, null=True)),
                ('asset_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.EveCharacter')),
                ('contract_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_scanner.Contract')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.Module')),
            ],
        ),
    ]
