# Generated by Django 2.0.9 on 2018-10-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("abyssal_modules", "0006_mutator_source_fk_part_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="mutator_type_id",
        ),
        migrations.RemoveField(
            model_name="module",
            name="source_type_id",
        ),
        migrations.AlterField(
            model_name="module",
            name="mutator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.InvType",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.InvType",
            ),
        ),
    ]
