# Generated by Django 2.1.3 on 2018-11-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0001_initial'),
        ('abyssal_modules', '0009_remove_moduledogmaattribute_icon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_modules', models.ManyToManyField(to='eve_sde.InvType')),
            ],
        ),
        migrations.CreateModel(
            name='MutatorAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_modifier', models.DecimalField(decimal_places=5, max_digits=10)),
                ('max_modifier', models.DecimalField(decimal_places=5, max_digits=10)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.TypeAttribute')),
                ('mutator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.Mutator')),
            ],
        ),
        migrations.AddField(
            model_name='mutator',
            name='attributes',
            field=models.ManyToManyField(through='abyssal_modules.MutatorAttribute', to='abyssal_modules.TypeAttribute'),
        ),
        migrations.AddField(
            model_name='mutator',
            name='item_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.InvType'),
        ),
        migrations.AddField(
            model_name='mutator',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abyssal_modules.ModuleType'),
        ),
    ]
