# Generated by Django 2.1.3 on 2018-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0010_mutators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattribute',
            name='value',
            field=models.FloatField(db_index=True),
        ),
    ]
