# Generated by Django 2.1.3 on 2018-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0011_value_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledogmaattribute',
            name='is_derived',
            field=models.BooleanField(default=False),
        ),
    ]
