# Generated by Django 2.1.3 on 2018-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abyssal_modules', '0015_rename_new_attribute'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW abyssal_modules_attributes__view AS
            SELECT
                P0."module_id",
                P0."static_module_id",
                P0."value",
                P0."attribute_id",
                P0."new_attribute_id",
                P1."type_id" AS "_type_id",
                P1."attribute_id" AS "_attribute_id"
            FROM
                "abyssal_modules_moduleattribute" AS P0
                INNER JOIN
                "abyssal_modules_typeattribute" AS P1
                ON (
                    P0."new_attribute_id" = P1."id"
                );
            """,
            reverse_sql="DROP VIEW IF EXISTS abyssal_modules_attributes__view;"
        ),
        migrations.RunSQL(
            """
            CREATE VIEW abyssal_modules_derived_attributes__view AS
            SELECT
                0 AS "id",
                "module_id",
                "static_module_id",
                "value",
                "attribute_id",
                "new_attribute_id"
            FROM
                abyssal_modules_attributes__view
            UNION
            SELECT
                0 AS "id",
                "module_id",
                "static_module_id",
                0.001 * "value" AS "value",
                10073 AS "attribute_id",
                (
                    SELECT
                        "id"
                    FROM
                        "abyssal_modules_typeattribute"
                    WHERE
                        "attribute_id" = 10073 AND
                        "type_id" = "_type_id"
                ) AS "new_attribute_id"
            FROM
                abyssal_modules_attributes__view
            WHERE
                _attribute_id = 73
            UNION
            SELECT
                0 AS "id",
                "module_id",
                "static_module_id",
                0.001 * "value" AS "value",
                11795 AS "attribute_id",
                (
                    SELECT
                        "id"
                    FROM
                        "abyssal_modules_typeattribute"
                    WHERE
                        "attribute_id" = 11795 AND
                        "type_id" = "_type_id"
                ) AS "new_attribute_id"
            FROM
                abyssal_modules_attributes__view
            WHERE
                _attribute_id = 1795
            UNION
            SELECT
                0 AS "id",
                "module_id",
                "static_module_id",
                100 * "value" AS "value",
                10147 AS "attribute_id",
                (
                    SELECT
                        "id"
                    FROM
                        "abyssal_modules_typeattribute"
                    WHERE
                        "attribute_id" = 10147 AND
                        "type_id" = "_type_id"
                ) AS "new_attribute_id"
            FROM
                abyssal_modules_attributes__view
            WHERE
                _attribute_id = 147
            UNION
            SELECT
                0 AS "id",
                "module_id",
                "static_module_id",
                100 * ("value" - 1) AS "value",
                10213 AS "attribute_id",
                (
                    SELECT
                        "id"
                    FROM
                        "abyssal_modules_typeattribute"
                    WHERE
                        "attribute_id" = 10213 AND
                        "type_id" = "_type_id"
                ) AS "new_attribute_id"
            FROM
                abyssal_modules_attributes__view
            WHERE
                _attribute_id = 213
            UNION
            SELECT
                0 AS "id",
                "module_id",
                "static_module_id",
                100 * (1 - "value") AS "value",
                10204 AS "attribute_id",
                (
                    SELECT
                        "id"
                    FROM
                        "abyssal_modules_typeattribute"
                    WHERE
                        "attribute_id" = 10204 AND
                        "type_id" = "_type_id"
                ) AS "new_attribute_id"
            FROM
                abyssal_modules_attributes__view
            WHERE
                _attribute_id = 204;
            """,
            reverse_sql="DROP VIEW IF EXISTS abyssal_modules_derived_attributes__view;"
        ),
        migrations.CreateModel(
            name='ModuleAttributeView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'abyssal_modules_derived_attributes__view',
                'managed': False,
            },
        )
    ]
