# Generated by Django 2.1.3 on 2018-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abyssal_modules", "0016_attribute_view"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW abyssal_modules_attribute_stats__view AS
            SELECT
                AVG("value"),
                STDDEV("value"),
                "new_attribute_id"
            FROM
                abyssal_modules_derived_attributes__view
            WHERE
                static_module_id IS NULL
            GROUP BY new_attribute_id;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS abyssal_modules_attribute_stats__view",
        ),
        migrations.CreateModel(
            name="ModuleAttributeAggregate",
            fields=[
                (
                    "new_attribute",
                    models.OneToOneField(
                        on_delete=models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="abyssal_modules.TypeAttribute",
                    ),
                ),
                ("avg", models.FloatField()),
                ("stddev", models.FloatField()),
            ],
            options={
                "db_table": "abyssal_modules_attribute_stats__view",
                "managed": False,
            },
        ),
    ]
