# Generated by Django 3.2.16 on 2023-01-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abyssal_modules", "0018_update_attribute_view_dc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeattribute",
            name="high_is_good",
            field=models.BooleanField(null=True),
        ),
    ]
