# Generated by Django 4.1.13 on 2024-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "abyssal_modules",
            "0020_alter_module_attributes_alter_moduletype_attributes_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(models.F("module__type_id"), name="module_type_id_idx"),
        ),
    ]
