# Generated by Django 4.1.13 on 2024-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abyssal_modules", "0021_moduleattribute_abyssal_mod_module__1ac629_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(
                fields=["module", "attribute", "-value"],
                name="abyssal_mod_module__ad8ba2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(
                fields=["module", "attribute", "value"],
                name="abyssal_mod_module__f6b215_idx",
            ),
        ),
    ]
