# Generated by Django 4.1.13 on 2024-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "abyssal_modules",
            "0022_moduleattribute_abyssal_mod_module__ad8ba2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(fields=["value"], name="abyssal_mod_value_8f8ca9_idx"),
        ),
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(fields=["-value"], name="abyssal_mod_value_c82602_idx"),
        ),
    ]
