# Generated by Django 4.1.13 on 2024-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "abyssal_modules",
            "0023_moduleattribute_abyssal_mod_value_8f8ca9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(
                models.F("attribute"),
                models.OrderBy(models.F("value")),
                name="attribute_value_asc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moduleattribute",
            index=models.Index(
                models.F("attribute"),
                models.OrderBy(models.F("value"), descending=True),
                name="attribute_value_desc_idx",
            ),
        ),
    ]
