# Generated by Django 2.0.5 on 2018-06-03 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Expired'), (2, 'Sold'), (3, 'Disappeared')], db_index=True)),
                ('issuer_id', models.BigIntegerField(db_index=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=32)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
