# Generated by Django 2.0.5 on 2018-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='known',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Expired'), (2, 'Sold'), (3, 'Disappeared'), (4, 'Canceled'), (5, 'Rejected'), (6, 'Deleted'), (9, 'Unknown')], db_index=True),
        ),
    ]
