# Generated by Django 2.0.5 on 2018-08-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0004_single_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='scanned',
        ),
    ]
