# Generated by Django 2.0.5 on 2018-08-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0005_remove_contract_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
