# Generated by Django 2.0.5 on 2018-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0006_available_as_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='location_id',
            field=models.BigIntegerField(db_index=True, default=60003760),
            preserve_default=False,
        ),
    ]
