# Generated by Django 2.0.5 on 2018-09-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_scanner", "0009_contract_region_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="modules",
            field=models.ManyToManyField(
                editable=False, related_name="contracts", to="abyssal_modules.Module"
            ),
        ),
    ]
