# Generated by Django 2.0.9 on 2018-11-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_scanner", "0011_contract_date_indices"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="plex",
            field=models.IntegerField(default=0),
        ),
    ]
