# Generated by Django 2.0.9 on 2018-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0012_contract_plex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexPriceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
