# Generated by Django 2.0.9 on 2018-11-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_scanner', '0013_plexpricerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plexpricerecord',
            options={'get_latest_by': 'time'},
        ),
    ]
