RELEVANT_ATTRIBUTES = {
    'microwarpdrive': [(6, False), (147, True), (20, True), (30, False), (554, False), (50, False)],
    'afterburner': [(6, False), (20, True), (30, False), (50, False)],
    'shield_extender': [(72, True), (50, False), (30, False), (983, False)],
    'armor_plates': [(50, False), (30, False), (796, False), (1159, True)],
    'shield_booster': [(50, False), (30, False), (68, True), (6, False), (73, False)],
    'armor_repairer': [(50, False), (30, False), (84, True), (6, False), (73, False)],
    'ancil_shield_booster': [(50, False), (30, False), (68, True), (6, False), (73, False), (1795, False)],
    'ancil_armor_repairer': [(50, False), (30, False), (84, True), (6, False), (73, False), (1795, False)],
    'energy_neutralizer': [(50, False), (30, False), (6, False), (54, True), (2044, True), (97, True)],
    'energy_nosferatu': [(50, False), (30, False), (54, True), (2044, True), (90, True)],
    'cap_battery': [(50, False), (30, False), (2267, False), (67, True)],
    'warp_scrambler': [(50, False), (6, False), (54, True), (105, True)],
    'warp_disruptor': [(50, False), (6, False), (54, True)],
    'stasis_webifier': [(50, False), (30, False), (6, False), (54, True), (20, False)],
    'damage_mod': [(50, False), (64, True), (204, True)],
    'damage_mod_bcs': [(50, False), (213, True), (204, True), (1255, True)],
    'damage_control': [(50, False), (974, False), (975, False), (976, False), (977, False)],
    'assault_damage_control': [(50, False), (73, True), (974, False), (975, False), (976, False), (977, False)],
    'drone_damage_amplifier': [(50, False), (1255, True)],
    'mutated_light_drone': [(64, True), (160, True), (37, True), (263, True), (9, True), (54, True), (265, True), (158, True)],
    'mutated_heavy_drone': [(64, True), (160, True), (37, True), (263, True), (9, True), (54, True), (265, True), (158, True)],
    'mutated_sentry_drone': [(64, True), (160, True), (263, True), (9, True), (54, True), (265, True), (158, True)],
    'mutated_medium_drone': [(64, True), (160, True), (37, True), (263, True), (9, True), (54, True), (265, True), (158, True)],
    'abyssal_fighter_support_unit': [(2336, True), (2337, True), (2338, True), (50, False), (30, False), (2335, True)],
    'abyssal_siege_module': [(2307, True), (2306, True), (2347, True), (2346, False), (30, False)],
}

ITEMS = [
    {
        "abyssal_id": 47749,
        "normal_id": 439,
        "name": "1MN Abyssal Afterburner",
        "relevant_attributes": RELEVANT_ATTRIBUTES['afterburner'],
    },
    {
        "abyssal_id": 47769,
        "normal_id": 523,
        "name": "Small Abyssal Armor Repairer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_repairer'],
    },
    {
        "abyssal_id": 47817,
        "normal_id": 11299,
        "name": "Medium Abyssal Armor Plates",
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_plates'],
    },
    {
        "abyssal_id": 47820,
        "normal_id": 11279,
        "name": "Large Abyssal Armor Plates",
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_plates'],
    },
    {
        "abyssal_id": 47836,
        "normal_id": 32772,
        "name": "Medium Abyssal Ancillary Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_shield_booster'],
    },
    {
        "abyssal_id": 47838,
        "normal_id": 4391,
        "name": "Large Abyssal Ancillary Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_shield_booster'],
    },
    {
        "abyssal_id": 47840,
        "normal_id": 32780,
        "name": "X-Large Abyssal Ancillary Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_shield_booster'],
    },
    {
        "abyssal_id": 47846,
        "normal_id": 33103,
        "name": "Large Abyssal Ancillary Armor Repairer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_armor_repairer'],
    },
    {
        "abyssal_id": 47781,
        "normal_id": 399,
        "name": "Small Abyssal Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_booster'],
    },
    {
        "abyssal_id": 47804,
        "normal_id": 3829,
        "name": "Medium Abyssal Shield Extender",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_extender'],
    },
    {
        "abyssal_id": 47808,
        "normal_id": 3839,
        "name": "Large Abyssal Shield Extender",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_extender'],
    },
    {
        "abyssal_id": 47828,
        "normal_id": 12265,
        "name": "Medium Abyssal Energy Neutralizer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_neutralizer'],
    },
    {
        "abyssal_id": 47736,
        "normal_id": 3242,
        "name": "Abyssal Warp Disruptor",
        "relevant_attributes": RELEVANT_ATTRIBUTES['warp_disruptor'],
    },
    {
        "abyssal_id": 47745,
        "normal_id": 12054,
        "name": "500MN Abyssal Microwarpdrive",
        "relevant_attributes": RELEVANT_ATTRIBUTES['microwarpdrive'],
    },
    {
        "abyssal_id": 47753,
        "normal_id": 12056,
        "name": "10MN Abyssal Afterburner",
        "relevant_attributes": RELEVANT_ATTRIBUTES['afterburner'],
    },
    {
        "abyssal_id": 47757,
        "normal_id": 12066,
        "name": "100MN Abyssal Afterburner",
        "relevant_attributes": RELEVANT_ATTRIBUTES['afterburner'],
    },
    {
        "abyssal_id": 47773,
        "normal_id": 3528,
        "name": "Medium Abyssal Armor Repairer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_repairer'],
    },
    {
        "abyssal_id": 47789,
        "normal_id": 10838,
        "name": "Large Abyssal Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_booster'],
    },
    {
        "abyssal_id": 47832,
        "normal_id": 12269,
        "name": "Heavy Abyssal Energy Neutralizer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_neutralizer'],
    },
    {
        "abyssal_id": 47702,
        "normal_id": 526,
        "name": "Abyssal Stasis Webifier",
        "relevant_attributes": RELEVANT_ATTRIBUTES['stasis_webifier'],
    },
    {
        "abyssal_id": 47732,
        "normal_id": 447,
        "name": "Abyssal Warp Scrambler",
        "relevant_attributes": RELEVANT_ATTRIBUTES['warp_scrambler'],
    },
    {
        "abyssal_id": 47777,
        "normal_id": 3538,
        "name": "Large Abyssal Armor Repairer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_repairer'],
    },
    {
        "abyssal_id": 47785,
        "normal_id": 10836,
        "name": "Medium Abyssal Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_booster'],
    },
    {
        "abyssal_id": 47800,
        "normal_id": 377,
        "name": "Small Abyssal Shield Extender",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_extender'],
    },
    {
        "abyssal_id": 47812,
        "normal_id": 11295,
        "name": "Small Abyssal Armor Plates",
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_plates'],
    },
    {
        "abyssal_id": 47824,
        "normal_id": 533,
        "name": "Small Abyssal Energy Neutralizer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_neutralizer'],
    },
    {
        "abyssal_id": 47842,
        "normal_id": 33076,
        "name": "Small Abyssal Ancillary Armor Repairer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_armor_repairer'],
    },
    {
        "abyssal_id": 47844,
        "normal_id": 33101,
        "name": "Medium Abyssal Ancillary Armor Repairer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_armor_repairer'],
    },
    {
        "abyssal_id": 47408,
        "normal_id": 12054,
        "name": "50MN Abyssal Microwarpdrive",
        "relevant_attributes": RELEVANT_ATTRIBUTES['microwarpdrive'],
    },
    {
        "abyssal_id": 47740,
        "normal_id": 434,
        "name": "5MN Abyssal Microwarpdrive",
        "relevant_attributes": RELEVANT_ATTRIBUTES['microwarpdrive'],
    },
    {
        "abyssal_id": 47793,
        "normal_id": 10840,
        "name": "X-Large Abyssal Shield Booster",
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_booster'],
    },
    {
        "abyssal_id": 48431,
        "normal_id": 1185,
        "name": "Small Abyssal Cap Battery",
        "relevant_attributes": RELEVANT_ATTRIBUTES['cap_battery'],
    },
    {
        "abyssal_id": 48435,
        "normal_id": 2018,
        "name": "Medium Abyssal Cap Battery",
        "relevant_attributes": RELEVANT_ATTRIBUTES['cap_battery'],
    },
    {
        "abyssal_id": 48439,
        "normal_id": 2020,
        "name": "Large Abyssal Cap Battery",
        "relevant_attributes": RELEVANT_ATTRIBUTES['cap_battery'],
    },
    {
        "abyssal_id": 48419,
        "normal_id": 530,
        "name": "Small Abyssal Energy Nosferatu",
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_nosferatu'],
    },
    {
        "abyssal_id": 48423,
        "normal_id": 12257,
        "name": "Medium Abyssal Energy Nosferatu",
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_nosferatu'],
    },
    {
        "abyssal_id": 48427,
        "normal_id": 12261,
        "name": "Heavy Abyssal Energy Nosferatu",
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_nosferatu'],
    },
    {
        "abyssal_id": 49730,
        "normal_id": 520,
        "name": "Abyssal Gyrostabilizer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['damage_mod'],
    },
    {
        "abyssal_id": 49722,
        "normal_id": 9944,
        "name": "Abyssal Magnetic Field Stabilizer",
        "relevant_attributes": RELEVANT_ATTRIBUTES['damage_mod'],
    },
    {
        "abyssal_id": 49726,
        "normal_id": 2363,
        "name": "Abyssal Heat Sink",
        "relevant_attributes": RELEVANT_ATTRIBUTES['damage_mod'],
    },
    {
        "abyssal_id": 49738,
        "normal_id": 47448,
        "name": "Abyssal Ballistic Control System",
        "relevant_attributes": RELEVANT_ATTRIBUTES['damage_mod_bcs'],
    },
    {
        "abyssal_id": 49734,
        "normal_id": 47908,
        "name": "Abyssal Entropic Radiation Sink",
        "relevant_attributes": RELEVANT_ATTRIBUTES['damage_mod'],
    },
    {
        "abyssal_id": 52227,
        "normal_id": 2048,
        "name": "Abyssal Damage Control",
        "relevant_attributes": RELEVANT_ATTRIBUTES['damage_control'],
    },
    {
        "abyssal_id": 52230,
        "normal_id": 47257,
        "name": "Abyssal Assault Damage Control",
        "relevant_attributes": RELEVANT_ATTRIBUTES['assault_damage_control'],
    },
    {
        "abyssal_id": 60482,
        "normal_id": 4393,
        "name": "Mutated Drone Damage Amplifier",
        "relevant_attributes": RELEVANT_ATTRIBUTES['drone_damage_amplifier'],
    },
    {
        "abyssal_id": 60478,
        "normal_id": 2203,
        "name": 'Mutated Light Drone',
        "relevant_attributes": RELEVANT_ATTRIBUTES['mutated_light_drone'],
    },
    {
        "abyssal_id": 60480,
        "normal_id": 2444,
        "name": 'Mutated Heavy Drone',
        "relevant_attributes": RELEVANT_ATTRIBUTES['mutated_heavy_drone'],
    },
    {
        "abyssal_id": 60481,
        "normal_id": 23561,
        "name": 'Mutated Sentry Drone',
        "relevant_attributes": RELEVANT_ATTRIBUTES['mutated_sentry_drone'],
    },
    {
        "abyssal_id": 60479,
        "normal_id": 2183,
        "name": 'Mutated Medium Drone',
        "relevant_attributes": RELEVANT_ATTRIBUTES['mutated_medium_drone'],
    },
    {
        "abyssal_id": 60483,
        "normal_id": 24283,
        "name": 'Abyssal Fighter Support Unit',
        "relevant_attributes": RELEVANT_ATTRIBUTES['abyssal_fighter_support_unit'],
    },
    {
        "abyssal_id": 56303,
        "normal_id": 40750,
        "name": 'Heavy Abyssal Warp Scrambler',
        "relevant_attributes": RELEVANT_ATTRIBUTES['warp_scrambler'],
    },
    {
        "abyssal_id": 56304,
        "normal_id": 40730,
        "name": 'Heavy Abyssal Warp Disrupter',
        "relevant_attributes": RELEVANT_ATTRIBUTES['warp_disruptor'],
    },
    {
        "abyssal_id": 56305,
        "normal_id": 41236,
        "name": '10000MN Abyssal Afterburner',
        "relevant_attributes": RELEVANT_ATTRIBUTES['afterburner'],
    },
    {
        "abyssal_id": 56306,
        "normal_id": 41249,
        "name": '50000MN Abyssal Microwarpdrive',
        "relevant_attributes": RELEVANT_ATTRIBUTES['microwarpdrive'],
    },
    {
        "abyssal_id": 56307,
        "normal_id": 20701,
        "name": 'Capital Abyssal Armor Repairer',
        "relevant_attributes": RELEVANT_ATTRIBUTES['armor_repairer'],
    },
    {
        "abyssal_id": 56308,
        "normal_id": 41503,
        "name": 'Capital Abyssal Ancillary Armor Repairer',
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_armor_repairer'],
    },
    {
        "abyssal_id": 56309,
        "normal_id": 20703,
        "name": 'Capital Abyssal Shield Booster',
        "relevant_attributes": RELEVANT_ATTRIBUTES['shield_booster'],
    },
    {
        "abyssal_id": 56310,
        "normal_id": 41504,
        "name": 'Capital Abyssal Ancillary Shield Booster',
        "relevant_attributes": RELEVANT_ATTRIBUTES['ancil_shield_booster'],
    },
    {
        "abyssal_id": 56311,
        "normal_id": 40665,
        "name": 'Capital Abyssal Energy Nosferatu',
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_nosferatu'],
    },
    {
        "abyssal_id": 56312,
        "normal_id": 40659,
        "name": 'Capital Abyssal Energy Neutralizer',
        "relevant_attributes": RELEVANT_ATTRIBUTES['energy_neutralizer'],
    },
    {
        "abyssal_id": 56313,
        "normal_id": 20280,
        "name": 'Abyssal Siege Module',
        "relevant_attributes": RELEVANT_ATTRIBUTES['abyssal_siege_module'],
    },
]

UNIT_STR = {
    1: 'm',
    2: 'kg',
    3: 'sec',
    4: 'A',
    5: 'K',
    6: 'mol',
    7: 'cd',
    8: 'm2',
    9: 'm3',
    10: 'm/sec',
    11: 'm/sec',
    12: 'm-1',
    13: 'kg/m3',
    14: 'm3/kg',
    15: 'A/m2',
    16: 'A/m',
    17: 'mol/m3',
    18: 'cd/m2',
    19: 'kg/kg = 1',
    101: 's',
    102: 'mm',
    103: 'None',
    104: 'x',
    105: '%',
    106: 'tf',
    107: 'MW',
    108: '%',
    109: '%',
    111: '%',
    112: 'rad/sec',
    113: 'HP',
    114: 'GJ',
    115: 'groupID',
    116: 'typeID',
    118: 'Ore units',
    119: 'attributeID',
    120: 'points',
    121: '%',
    122: 'None',
    123: 'sec',
    124: '%',
    125: 'N',
    126: 'ly',
    127: '%',
    128: 'Mbit/sec',
    129: 'None',
    133: 'ISK',
    134: 'm3/hour',
    135: 'AU',
    136: 'Slot',
    138: 'units',
    139: '+',
    140: 'Level',
    141: 'hardpoints',
    143: 'None',
}
