# Disable this for production environments.
DEBUG: false

# Make sure this is set to something secure in production.
SECRET_KEY: "123455"

# Optionally supply a Sentry DSN. May also be commented.
SENTRY_DSN: "https://[...]@sentry.io/[...]"

# Optionally supply a GitHub tracking ID. May be commented.
GA_TRACKING_ID: "XX-YYYYYYYY-Y"

# Set ESI client details.
ESI_CLIENT_ID: "123"
ESI_SECRET_KEY: "456"

# Set the root of the callback, including protocol and trailing shash but
# excluding the /auth/callback/ portion.
ESI_CALLBACK_ROOT: "https://mutaplasmid.space/"

# Set the ESI user agent name.
ESI_USER_AGENT: "[NAME]'s instance of mutaplasmid.space"

# Set the root website name, without prefix or slashes.
HOSTNAME: "mutaplasmid.space"

# Set the environment name (probably "prod", "stage", or "dev")
ENVIRONMENT_NAME: "environment"
